[package]
name = "some_transport"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
async-broadcast = "0.7.2"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { version = "1", features = ["full"] }
async-trait.workspace = true
bytes = "1.10.1"
uuid = { version = "1.17.0", features = ["v4"] }

[lints]
workspace = true
