global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - 'first_ruls.yml'

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Axum server
  - job_name: 'file_host'
    static_configs:
      - targets: ['host.docker.internal:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s
