---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - 'first_rules.yml'

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Axum server
  - job_name: 'file_host'
    static_configs:
      - targets: ['file-host-server:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Sys Info
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  # Process-level metrics
  - job_name: 'process_exporter'
    static_configs:
      - targets: ['process-exporter:9256']

  # Container-level metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
