[package]
name = "some-transport"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
async-broadcast = "0.7.2"
async-trait.workspace = true
dashmap = "6.1.0"
thiserror.workspace = true

[lints]
workspace = true

[features]
default = []              # features enabled by default
inmem = []            # simple feature, nothing else enabled

