[package]
name = "some-transport"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
async-broadcast = { version =  "0.7.2", optional = true }
async-trait.workspace = true
dashmap = { version =  "6.1.0", optional = true }
thiserror.workspace = true
serde = { workspace = true, features = ["derive"], optional = true }

serde_json = { workspace = true, optional = true }
async-nats = { version = "0.44.2", optional = true }
tokio  = { workspace = true, optional = true, features = ["sync"] }
futures = { version = "0.3", optional = true }
prost = { version = "0.14.1", optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[lints]
workspace = true

[features]
default = []              # features enabled by default
inmem = ["async-broadcast", "dashmap"]
nats = ["async-nats", "serde", "dashmap", "tokio/sync", "futures", "prost"]

