[package]
name = "ws-connection"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
dashmap = "6.1.0"
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }
tracing.workspace = true
uuid = { version = "1.18.1", features = ["v4", "fast-rng"] }

[lints]
workspace = true
