name: Build Image
on:
  workflow_call:
    inputs:
      matrix:
        description: "JSON array of image specs"
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(inputs.matrix) }}
    env:
      IMAGE_NAME: ${{ matrix.repo_suffix }}
      DOCKER_REPO: pgathondu/${{ matrix.repo_suffix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Prepare SQLx + migrations
        if: matrix.needs_sqlx == true || matrix.needs_migrations == true
        uses: ./.github/actions/prepare-sqlx
        with:
          image-name: ${{ matrix.name }}
          needs-sqlx: ${{ matrix.needs_sqlx }}
          needs-migrations: ${{ matrix.needs_migrations }}
          migration-paths: ${{ toJSON(matrix.migration_paths) }}
      - name: Build & Push
        uses: ./.github/actions/docker-build
        with:
          dockerfile: ${{ matrix.dockerfile }}
          image-name: ${{ env.IMAGE_NAME }}
          docker-repo: ${{ env.DOCKER_REPO }}
